---
title: CoTech
long_title: Cooperative Technologists
description: Building a tech industry that's better for its workers and customers through co-operation, democracy and worker ownership.
timezone: UTC
url: https://www.coops.tech
exclude:
- scripts
- vendor
- .idea
collections:
  coops:
    title: Coops
    output: true
    permalink: "/co-op/:name"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: coops
  values:
    layout: coop
forum: https://community.coops.tech/
