---
title: Cotech Website
timezone: UTC
url: https://www.coops.tech
exclude:
- scripts
- vendor
- .idea
collections:
  clients:
    title: Clients
    output: false
  coops:
    title: Coops
    output: true
    permalink: "/co-op/:name"
  posts:
    title: Posts
    output: true
  services:
    title: Services
    output: true
    permalink: "/service/:name"
  technologies:
    title: Technologies
    output: true
    permalink: "/technology/:name"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: coops
  values:
    layout: coop
- scope:
    path: ''
    type: services
  values:
    layout: service
- scope:
    path: ''
    type: technologies
  values:
    layout: technology
forum: https://community.coops.tech/
mapbox_access_token: pk.eyJ1IjoiY290ZWNoIiwiYSI6ImNpemgxbzhwODAwMHMzM28zdXF3cGxyYmwifQ.9nPExuEUqwblCCl-6gyFXA
